controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

weather_get:
    path: /weather/get
    controller: App\Weather\UI\Controller\GetWeatherAction
